import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import classNames from "classnames";
import Style from "./layout.module.css";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, modal
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className={classNames(geistSans.variable, geistMono.variable, Style.Html)}
    >
      <body className={Style.Body}>
      <header className={Style.Header}>Новости</header>
      <main>
          <div className={Style.Modal}>
              {modal}
          </div>
           {children}</main>
      </body>
    </html>
  );
}
